name: Check PR Format and Test for cloudflare-workers

on:
  pull_request:
    branches:
      - master

jobs:
  check-format:
    name: Check PR Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloudflare-workers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Set Node.js 24.x
        with:
          node-version: 24.x
      - uses: borales/actions-yarn@v5
        name: Run install
        with:
          cmd: install
          dir: cloudflare-workers
      - uses: borales/actions-yarn@v5
        name: Check Format
        with:
          cmd: prettier --check .
          dir: cloudflare-workers

  test:
    name: Test PR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloudflare-workers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Set Node.js 24.x
        with:
          node-version: 24.x
      - uses: borales/actions-yarn@v5
        name: Run install
        with:
          cmd: install
          dir: cloudflare-workers
      - uses: borales/actions-yarn@v5
        name: Run Tests
        with:
          cmd: test
          dir: cloudflare-workers